sudo: required

language: python

python:
  - "3.4"

services:
  - docker

cache:
  - apt
  
env:
  - MONGO_IMAGE=mongo:3.4 REDIS_IMAGE=redis:latest DOCKER_OPTIONS="-e USE_MONGO_SERVER=1 -e SHORTURL_DB_URL=mongodb://mongodb/shorturl_test --link=mongodb:mongodb -e SHORTURL_REDIS_URL=redis://redis:6379/0 --link=redis:redis --rm"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install docker-engine
  - docker pull $MONGO_IMAGE
  - docker pull $REDIS_IMAGE
  - docker run -d --name=mongodb $MONGO_IMAGE mongod --noauth 
  - docker run -d --name=redis $REDIS_IMAGE redis-server --appendonly yes 
  - docker build -t shortener_url --build-arg mode=tests .
  - pip install coveralls
 
before_script:
  - sleep 15
  - env
  - docker run $DOCKER_OPTIONS shortener_url pip freeze

script:
  - docker run $DOCKER_OPTIONS -e COVERAGE_FILE=/coverage/.coverage -v $PWD/coverage:/coverage shortener_url nosetests --with-coverage -s -v shortener_url
  - docker run $DOCKER_OPTIONS shortener_url flake8 --exit-zero shortener_url
  
after_script: COVERAGE_FILE=./coverage/.coverage coveralls --verbose

notifications:
  email:
    on_success: always
    on_failure: always